// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNIpezgazdTpYq22keC-b_32aOQZvPFPk',
    appId: '1:811445642535:web:fdf062bc29434874baf502',
    messagingSenderId: '811445642535',
    projectId: 'bolu-ee1da',
    authDomain: 'bolu-ee1da.firebaseapp.com',
    storageBucket: 'bolu-ee1da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc1IG-l_AF0pKHXiTYIXrWzgekGqjXXIo',
    appId: '1:811445642535:android:c39ebfdf1f6a7f21baf502',
    messagingSenderId: '811445642535',
    projectId: 'bolu-ee1da',
    storageBucket: 'bolu-ee1da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy5jMzA_BTwXbQba3b4Oh7vMJOcZA05R0',
    appId: '1:811445642535:ios:31c84ae3d14381a8baf502',
    messagingSenderId: '811445642535',
    projectId: 'bolu-ee1da',
    storageBucket: 'bolu-ee1da.appspot.com',
    iosBundleId: 'com.example.bolluApp',
  );
}
